---

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      PERL_MM_USE_DEFAULT: 1
    strategy:
      matrix:
        os: 'windows-latest'
        perl: ['5.30', '5.28']
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup perl
        run: |
          choco install openssl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: perl -V
      - name: Install Dependencies
        run: |
          cpanm -qin File::Spec ExtUtils::MakeMaker
          cpanm -v Net::SSLeay
          cpanm -qin --skip-satisfied Test::Pod::Spelling::CommonMistakes Test::Portability::Files Test::Pod::Coverage
          cpanm -iq --installdeps --notest .
      - name: Run Tests
        run: prove -l t
